### ISSUE TITLE
Need functionality to show workout stats after workout

### ISSUE THREAD

**Issue by mbedmutha** [aarshia4481/UCSD-CSE-118-218-Team-A#21]
Shows the user's summary of workout
Similar summaries of friends should available on request.
Should use `get-workout-summary` as an endpoint

Usage:
- How did I do today? `get-workout-summary?alexa_id=<id>`
- How did <Friend> do today? `get-workout-summary?alexa_id=<id>&participant_name=<friend>`

Server side should convert each friend slot into lower case (or specific convention)
AMAZON.firstname uses Title case

**Comment by fellinn** [comment]
https://127.0.0.1:5000/get-workout-summary?alexa_id=1
https://127.0.0.1:5000/get-workout-summary?alexa_id=1&participant_name=participant1

endpoint works the same as live-metrics. With the only parameter alexa_id the current participants data is returned.
if in addition participant_name is passed, the data of the resp. participant is returned
